# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics', models.DecimalField(decimal_places=2, max_digits=8)),
                ('movies', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bar', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='clothes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.Clothes'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='entertainment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.Entertainment'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='miscellaneous',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.Miscellaneous'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='savings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.Savings'),
        ),
    ]
